title : realTRIPS
tagline: 'realTRIPS'
author :
  name : Chen Zhong
  github : cchenzzhong
  twitter : cecile.zhong
keywords: big data, urban mobility, urban models, urban analytics


description: > # this means to ignore newlines until "baseurl:"
    

#baseurl: "https://urban-analytics.github.io/dust" # the subpath of your site, e.g. /blog/
baseurl: /realTRIPS
#url: https://urban-analytics.github.io

twitter_username: cecile.zhong
github_username:  cchenzzhong
email: c.zhong@ucl.ac.uk


# Define how blog permalinks should be constructed
permalink: /:year/:month/:title.html
# (the default:)
#permalink: /:categories/:year/:month/:day/:title.html

# Build settings
markdown: kramdown

exclude: [.scss, README.md, node_modules, gruntfile.js, package.json]
